# Generated by Django 2.2 on 2020-08-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['datetime'], 'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['datetime'], 'verbose_name': 'Enquiry', 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='franchise',
            options={'ordering': ['datetime'], 'verbose_name': 'Franchise', 'verbose_name_plural': 'Franchises'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
