# Generated by Django 2.2 on 2020-08-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200822_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='membership',
            field=models.CharField(blank=True, choices=[('Silver', 'silver'), ('Gold', 'gold'), ('Platinum', 'Platinum')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='name_of_contact_person',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='name_of_firm',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
