# Generated by Django 2.2 on 2020-08-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200822_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Private Firm', 'Private'), ('Government Firm', 'Government')], default='Private', max_length=100),
        ),
    ]
