# Generated by Django 2.2 on 2020-08-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200822_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
