# Generated by Django 2.2 on 2020-08-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_franchise_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='membership',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='name_of_contact_person',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='name_of_firm',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='phone',
            field=models.BigIntegerField(default=None),
        ),
    ]
