# Generated by Django 2.2 on 2020-08-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200822_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='membership',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Silver', max_length=100),
        ),
    ]
