# Generated by Django 2.2 on 2020-08-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200824_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='membership',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Private Firm', 'Private'), ('Government Firm', 'Government')], max_length=100),
        ),
    ]
